radius= input("enter radius")
pie= input("enter pie")
area= float(pie) *float(radius)**2
print(area)
print("*" * 10)
name= ("john smith")
age= (20)
patient= ("new")
patient_type= (name int(age) patient)
print(patient_type)